name: CI

on:
  push:
    branches: [ main, 'ci/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run unit tests (if present)
        # Run tests only if a 'test' script is defined in package.json. This avoids failing the job when no tests are configured.
        run: |
          npm run test --if-present

      - name: Install Firebase CLI (for emulator)
        run: npm install -g firebase-tools

      - name: Start Firestore emulator
        run: |
          npx firebase emulators:exec --only firestore --project=demo "echo 'emulator started'"
        env:
          # Ensure the emulator runs on default host/port and exposes env var
          FIRESTORE_EMULATOR_HOST: localhost:8080

      - name: Run emulator integration tests
        run: |
          echo "Running integration tests against Firestore emulator"
          npm run test:integration:emulator

      - name: Upload build artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
