name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers and system dependencies
        # Use the Playwright CLI installer which handles browser binaries and
        # platform-specific dependency installation for supported runners.
        run: |
          npx playwright install --with-deps
        env:
          CI: true

      - name: Build production and run Playwright E2E
        run: |
          npm run build
          # Serve the production build and run playwright against it. e2e:prod
          # should start the server (or use a serve script) and then run tests.
          npm run e2e:prod
        env:
          CI: true
