name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        # Use explicit install to avoid deprecated/OS-specific action behavior.

      - name: Build and run E2E against production build
        run: |
          npm run e2e:prod
        env:
          CI: true

      - name: List test-results (for debug)
        if: always()
        run: |
          echo "--- ls test-results ---"
          ls -la test-results || true
          echo "--- find relevant artifacts ---"
          find . -type f -name "*.zip" -o -name "*.webm" -o -name "trace.zip" -o -name "*.log" || true

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-${{ github.run_id }}
          path: |
            test-results/**
            test-results/**/*
            playwright-report/**
            test-results/**/*.zip
            **/trace.zip
            **/video/**
            **/*.webm
            **/*.log
