name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1
        # This action installs Playwright and the browser binaries and helps
        # ensure the environment has the required dependencies on the runner.

      - name: Build and run E2E against production build
        run: |
          npm run e2e:prod
        env:
          CI: true
