name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *' # nightly full run at 03:00 UTC
  workflow_dispatch:

jobs:
  e2e-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        # Use explicit install to avoid deprecated/OS-specific action behavior.

      - name: Start dev server (background)
        run: |
          nohup bash -lc 'HOST=127.0.0.1 PORT=5173 npm run dev:ci' > vite.log 2>&1 &
          echo $! > vite.pid
          echo "Started dev server PID: $(cat vite.pid)"
          # Wait for server to respond
          for i in {1..60}; do
            if curl -sSf http://127.0.0.1:5173 > /dev/null; then echo "Dev server ready"; break; fi
            echo "waiting for dev server... $i"
            sleep 1
          done

      - name: Run smoke E2E against dev server (Admin lazy-load only)
        env:
          CI: true
          E2E_USE_DEV: '1'
          FORCE_TRACE: '1'
        run: |
          # Ensure Playwright uses the dev server
          npx playwright test tests/e2e/admin-lazy.spec.ts -g "Admin lazy-load" --reporter=list --trace on

      - name: List test-results (for debug)
        if: always()
        run: |
          echo "--- ls test-results ---"
          ls -la test-results || true
          echo "--- find relevant artifacts ---"
          find . -type f -name "*.zip" -o -name "*.webm" -o -name "trace.zip" -o -name "*.log" || true

      - name: Stop dev server
        if: always()
        run: |
          if [ -f vite.pid ]; then kill $(cat vite.pid) || true; fi

      - name: Bundle artifacts (smoke)
        if: always()
        run: |
          mkdir -p artifacts-smoke
          cp -R test-results artifacts-smoke/ || true
          cp -R playwright-report artifacts-smoke/ || true
          [ -f vite.log ] && cp vite.log artifacts-smoke/ || true
          tar -czf artifacts-smoke.tgz artifacts-smoke || true

      - name: Upload Playwright artifacts (smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-smoke-${{ github.run_id }}
          path: |
            test-results/**
            test-results/**/*
            playwright-report/**
            test-results/**/*.zip
            **/trace.zip
            **/video/**
            **/*.webm
            **/*.log
            vite.log
            artifacts-smoke.tgz

  e2e-full:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start dev server (background)
        run: |
          nohup bash -lc 'HOST=127.0.0.1 PORT=5173 npm run dev:ci' > vite.log 2>&1 &
          echo $! > vite.pid
          echo "Started dev server PID: $(cat vite.pid)"
          for i in {1..60}; do
            if curl -sSf http://127.0.0.1:5173 > /dev/null; then echo "Dev server ready"; break; fi
            echo "waiting for dev server... $i"
            sleep 1
          done

      - name: Run full E2E against dev server
        env:
          CI: true
          E2E_USE_DEV: '1'
          FORCE_TRACE: '1'
        run: |
          npx playwright test --reporter=list --trace on

      - name: Stop dev server
        if: always()
        run: |
          if [ -f vite.pid ]; then kill $(cat vite.pid) || true; fi

      - name: Bundle artifacts (full)
        if: always()
        run: |
          mkdir -p artifacts-full
          cp -R test-results artifacts-full/ || true
          cp -R playwright-report artifacts-full/ || true
          [ -f vite.log ] && cp vite.log artifacts-full/ || true
          tar -czf artifacts-full.tgz artifacts-full || true

      - name: Upload Playwright artifacts (full)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-full-${{ github.run_id }}
          path: |
            test-results/**
            test-results/**/*
            playwright-report/**
            test-results/**/*.zip
            **/trace.zip
            **/video/**
            **/*.webm
            **/*.log
            vite.log
            artifacts-full.tgz
